version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
      # - "4000:4000"
      # - "3000:4000"
    volumes:
      - ./:/app
      - /app/node_modules #pequeño hack para no subir node_modules
    environment:
      - PORT=3000
  #postgres:
  #mongo:
